#!/usr/bin/env python3
"""
Generate a screen-ui Font .c file from a TTF using ttf2ugui.

Usage: python3 fonts/gen_font.py <font.ttf> <size_px> <symbol>

  font.ttf — path to TrueType font
  size_px  — font size in pixels
  symbol   — C symbol name (e.g. font_noto12)

Output: <symbol>.c written next to this script.
Requires: ../../ttf2ugui/ttf2ugui binary.
"""
import re, sys, os, subprocess, tempfile

HERE    = os.path.dirname(os.path.abspath(__file__))
TTFUGUI = os.path.join(HERE, '../../ttf2ugui/ttf2ugui')


def parse_hex(text):
    # Strip // comments before scanning — bitmap lines end with "// 0x20  32  ' '"
    # which would otherwise inject spurious bytes into the array.
    clean = '\n'.join(line.split('//')[0] for line in text.splitlines())
    return [int(x, 16) for x in re.findall(r'0x[0-9A-Fa-f]{2}', clean)]


def main():
    if len(sys.argv) < 4:
        sys.exit(__doc__)

    font_path = os.path.abspath(sys.argv[1])
    size      = sys.argv[2]
    sym       = sys.argv[3]

    with tempfile.TemporaryDirectory() as tmp:
        r = subprocess.run(
            [TTFUGUI, '--dump', f'--font={font_path}', f'--size={size}'],
            capture_output=True, text=True, cwd=tmp)
        files = [f for f in os.listdir(tmp) if f.endswith('.c')]
        if not files:
            sys.exit(f"ttf2ugui failed:\n{r.stderr.strip()}")
        with open(os.path.join(tmp, files[0])) as f:
            src = f.read()

    m = re.search(r'UG_FONT \S+\[\] = \{(.*?)\};', src, re.DOTALL)
    if not m:
        sys.exit("Cannot parse UG_FONT array")
    raw = parse_hex(m.group(1))

    char_w      = raw[0]
    char_h      = raw[1]
    n_chars     = (raw[2] << 8) | raw[3]
    offset_size = (raw[4] << 8) | raw[5]
    bpc         = (raw[6] << 8) | raw[7]   # bytes_per_char = h * stride
    flags       = raw[8]
    has_widths  = bool(flags & 0x40)
    stride      = bpc // char_h
    first       = 32                        # ttf2ugui default range: ' ' to '~'

    pos = 9
    widths = None
    if has_widths:
        widths = raw[pos : pos + n_chars]
        pos += n_chars
    pos += offset_size                      # skip offsets table
    bitmaps = raw[pos : pos + n_chars * bpc]

    outfile = os.path.join(HERE, sym + '.c')
    with open(outfile, 'w') as out:
        base = os.path.basename(font_path)
        out.write(f'// Generated by fonts/gen_font.py\n')
        out.write(f'// {base}  size={size}  ->  {char_w}x{char_h}  chars {first}-{first+n_chars-1}\n\n')
        out.write('#include <stdint.h>\n#include "fonts.h"\n\n')

        out.write(f'static const uint8_t {sym}_data[{n_chars}][{bpc}] = {{\n')
        for i in range(n_chars):
            ch  = first + i
            row = bitmaps[i * bpc : (i + 1) * bpc]
            hex_str = ','.join(f'0x{b:02X}' for b in row)
            out.write(f'    [{i}] = {{{hex_str}}}, // {repr(chr(ch))}\n')
        out.write('};\n\n')

        if widths:
            out.write(f'static const uint8_t {sym}_widths[{n_chars}] = {{\n    ')
            for i, w in enumerate(widths):
                out.write(f'{w},')
                if (i + 1) % 16 == 0:
                    out.write('\n    ')
            out.write('\n};\n\n')

        out.write(f'const Font {sym} = {{\n')
        out.write(f'    .w      = {char_w},\n')
        out.write(f'    .h      = {char_h},\n')
        out.write(f'    .stride = {stride},\n')
        out.write(f'    .first  = {first},\n')
        out.write(f'    .count  = {n_chars},\n')
        out.write(f'    .data   = &{sym}_data[0][0],\n')
        if widths:
            out.write(f'    .widths = {sym}_widths,\n')
        out.write('};\n')

    print(f'Wrote {outfile}  ({char_w}x{char_h}, {n_chars} chars, widths={has_widths})')


main()
